<?php

namespace App\Http\Controllers\Wechat;

/**
 * SMTP邮件发送
 */


class OfficialAccountController extends WechatController
{
    protected $settingArray = [
        'setting.wechat.official.account.app.id'=>null,
        'setting.wechat.official.account.secret' =>null,
        'setting.wechat.official.account.token' =>null,
        'setting.wechat.official.account.aes.key'=>null
    ];

    protected function getSetting()
    {
        return parent::getSettingFun($this->settingArray);
    }

    public function configInputForm()
    {
        $this->getSetting();
        return [
            '微信公众号'=>
                [
                    'app_id' =>'setting.wechat.official.account.app.id',
                    'secret' =>'setting.wechat.official.account.secret',
                    'token' =>'setting.wechat.official.account.token',
                    'aes_key' =>'setting.wechat.official.account.aes.key',
                ]
        ];
    }

    public function getConfigArr()
    {
        $setting = $this->getSetting();
        return [
            'app_id' => $setting['setting.wechat.official.account.app.id'],
            'secret' => $setting['setting.wechat.official.account.secret'],
            'token' => $setting['setting.wechat.official.account.token'],
            'aes_key' => $setting['setting.wechat.official.account.aes.key'],
            'response_type' => 'array',
        ];
    }

    public function setConfig()
    {
        parent::setConfig(); // TODO: Change the autogenerated stub
        $setting = $this->getSetting();
        config(['wechat.official_account.default.app_id'=>$setting['setting.wechat.official.account.app.id']]);
        config(['wechat.official_account.default.secret'=>$setting['setting.wechat.official.account.secret']]);
        config(['wechat.official_account.default.token'=>$setting['setting.wechat.official.account.token']]);
        config(['wechat.official_account.default.aes_key'=>$setting['setting.wechat.official.account.aes.key']]);
    }
}